services:

  postgres:
    image: postgres:17
    container_name: fluxa-postgres
    environment:
      POSTGRES_DB: fluxa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ld0423
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: fluxa-backend
    depends_on:
      - postgres
    env_file:
      - .env.docker
    ports:
      - "8080:8080"

volumes:
  postgres_data: